#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=02:00:00
#PBS -N mark_bad_raw

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Franco Pestilli

set -e
set -x


# make output directory
mkdir -p out_dir
mkdir -p out_figs

# run the actual python code
singularity exec docker://brainlife/mne:1.2.1 python3 main.py